# Generated by Django 5.0.3 on 2024-03-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0003_alter_contact_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Email',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
