# Generated by Django 5.0.3 on 2024-03-19 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0004_alter_contact_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Email',
            new_name='email',
        ),
    ]
