# Generated by Django 5.0.3 on 2024-03-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0006_alter_contact_email_alter_contact_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default='rijan', max_length=255),
            preserve_default=False,
        ),
    ]
