# Generated by Django 4.2.13 on 2024-06-26 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0008_contact_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='password',
        ),
    ]
